
export enum CommandType {
    LOCK = 'LOCK',
    MESSAGE = 'MESSAGE',
    SCREENSHOT = 'SCREENSHOT',
    SHUTDOWN = 'SHUTDOWN',
    RESTART = 'RESTART',
    LOG_OUT = 'LOG_OUT',
    UPDATE = 'UPDATE',
    CUSTOM = 'CUSTOM',
    FIREWALL_ON = 'FIREWALL_ON',
    FIREWALL_OFF = 'FIREWALL_OFF',
}